# Generated by Django 3.2.7 on 2021-12-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_active_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_order',
            name='tortal_price',
        ),
        migrations.AddField(
            model_name='active_order',
            name='total_price',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
