# Generated by Django 3.2.7 on 2021-12-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211209_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_order',
            name='address',
            field=models.TextField(),
        ),
    ]
