# Generated by Django 3.2.7 on 2021-12-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_active_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_order',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
