# Generated by Django 3.2.7 on 2021-12-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_active_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
