# Generated by Django 3.2.7 on 2021-12-15 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_auto_20211212_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cast',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='History_Cast',
            new_name='History_Cart',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cast',
            new_name='cart',
        ),
        migrations.RemoveField(
            model_name='history_cart',
            name='casts',
        ),
        migrations.AddField(
            model_name='history_cart',
            name='carts',
            field=models.ManyToManyField(to='order.Cart'),
        ),
    ]
