# Generated by Django 4.0.1 on 2022-01-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20220104_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
