# Generated by Django 3.2.7 on 2021-11-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_image',
            field=models.ManyToManyField(default='static/image/products/default.png', to='products.Description_image'),
        ),
    ]
