# Generated by Django 3.2.7 on 2021-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_image',
            field=models.ManyToManyField(blank=True, to='products.Description_image'),
        ),
    ]
